### ISSUE TITLE
[Feature Request] 请求添加对于行内代码块的支持

### ISSUE THREAD

**Issue by zhuozhiyongde** [LongYinStudio/vscode-typora-shortcut-key#1]
如题，希望能够支持 cmd + ` 激活

\`$1\`$2 这个 Snippet，或者对选中部分加这个符号

感谢作者！

**Comment by LongYinStudio** [comment]
已经发布v1.4.0，已实现该功能，去更新试试是不是你想要的功能

**Comment by LongYinStudio** [comment]
v1.4.1 解决 lineCode 切换不能删除``而是再套一层的问题

**Comment by LongYinStudio** [comment]
解决 lineCode 所选内容在的行已有\`内容\`，而导致切换\`\`所删除字符串不对

**Comment by zhuozhiyongde** [comment]
感谢作者，确实是我想要的，但是默认按键 ctrl+ \` 和打开切换终端冲突，建议换为 alt+\`

另外如果能进一步支持代码块（\`\`\`）和公式块（\$\$）就更好啦！

以及 README 里可以提一句，如果无效，可以去 shortcut 里自行调整按键绑定（即事件已经注册了）可能会更利于用户使用呢？

再次感谢作者，真的很好用！

**Comment by LongYinStudio** [comment]
好的
