### ISSUE TITLE
请求支持快捷键光标跳转

### ISSUE THREAD

**Issue by zhuozhiyongde** [LongYinStudio/vscode-typora-shortcut-key#2]
如题，现有的 alt+\` ，在未选中文本的时候，会把光标移动到第二个 \` 后，希望能够放到第一个\`和第二个\` 之间，同 Typora；

另外，现有的 cmd+k，希望能够移除占位文本，不然每次都需要手动删除/选中，也是略有不便，同时也希望其能像 Typora 一样光标移动到 \[\] 中间；

感谢大佬！

**Comment by LongYinStudio** [comment]
好了，更新下试试呢

**Comment by zhuozhiyongde** [comment]
感谢！现在光标跳转正常了，但还是希望能够移除占位文本（包括代码块啥的），因为实际上不是每个链接都会设置title，以及手动选中URL还是有点麻烦了x

**Comment by LongYinStudio** [comment]
好了，写了个配置项（是否启用注释）

**Comment by zhuozhiyongde** [comment]
感谢大佬！
