### ISSUE TITLE
在行开头有空格的时候出现问题。

### ISSUE THREAD

**Issue by zhuozhiyongde** [LongYinStudio/vscode-typora-shortcut-key#5]
如题，现在的工作选取包含

```
line.firstNonWhitespaceCharacterIndex
```

这会让行首有空格的时候工作出现问题：

https://github.com/LongYinStudio/vscode-typora-shortcut-key/assets/36695271/3d9ff7b5-7c9c-4025-97b4-c468d4cd2aba

**Comment by LongYinStudio** [comment]
已解决
